site_name: 'SurfersLookout Accelerator'
repo_url: https://github.com/davlloyd/surfers-flask-accelerator
repo_name: Github
edit_uri: blob/main/docs/
docs_dir: docs
nav:
  - Home: index.md
plugins:
  - techdocs-core
