
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: surfersflaskaccelerator
  namespace: alpha
  description: Surf Forecast Accelerator
  tags:
    - app-accelerator
    - python
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=surferslookout'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:surfers-crew
  system: surfers-system
